### ISSUE TITLE
PIN reuse across multiple devices

### ISSUE THREAD

**Issue by robinkrahl** [d-e-s-o/nitrocli#24] opened 2018-12-19 20:05 UTC
`nitrocli` does not keep track of the device it connects to.  If a user switches between two devices without clearing the passphrase cache, `nitrocli` will try to connect to device A using the cached passphrase for device B.  This is not a major issue, but I think we could improve `nitrocli`’s behavior by
- adding the serial number (and maybe the model?) of the connected Nitrokey to the pinentry dialog, and
- making sure that we do not reuse a cached passphrase for another device.

I was thinking of two ways to implement the second point:  Firstly, we could add the serial number to the ID of the cached passphrase (e. .g `nitrocli:admin:deadbeef` instead of `nitrocli:admin`).  This would make it harder to clear the cache with the `clear` command as we either would have to keep track of the passphrase IDs or could only clear the passphrases for the current device.  Secondly, we could store the serial number together with the stored passphrase (with a separate cache ID or as a prefix for the passphrase).  But it is unclear whether `PRESET_PASSPHRASE` is applicable for custom passphrases, and it is not enabled by default.  So we cannot set the passphrase without user interaction.

**Comment by d-e-s-o** [comment] 2018-12-20 03:59
Interesting, yeah that is a bit of a problem. Thanks for pointing that out.

I am not sure I fully understand the problem you mention with the second approach:

> But it is unclear whether `PRESET_PASSPHRASE` is applicable for custom passphrases, and it is not enabled by default.

I can't follow this part. What do you mean by "applicable for custom passphrases"? That we can't store arbitrary data? And what exactly is not enabled by default?

I honestly think that the first approach is fine, where the `clear` would only affect the currently plugged-in device. Swapping devices like that is a rare case, I would argue. And even so the behavior is still reasonable.

**Comment by robinkrahl** [comment] 2018-12-20 11:35
> I can't follow this part. What do you mean by "applicable for custom passphrases"? That we can't store arbitrary data? 

The documentation for [`PRESET_PASSPHRASE`][] refers to the “cache for the specified *keygrip*”, while `GET_PASSPHRASE` and `CLEAR_PASSPHRASE` just refer to cache IDs.  I don’t know whether this is just inconsistent/outdated documentation, or whether `PRESET_PASSPHRASE` really only applies to keys managed by GPG.

> And what exactly is not enabled by default?

The `PRESET_PASSPHRASE` command:
```
$ gpg-connect-agent "PRESET_PASSPHRASE test" "/bye"
ERR 67108924 Not supported <GPG Agent> - no --allow-preset-passphrase
```

> I honestly think that the first approach is fine, where the `clear` would only affect the currently plugged-in device. Swapping devices like that is a rare case, I would argue. And even so the behavior is still reasonable.

I agree.  I think this will mostly benefit us – at least I noticed the problem when switching between my production stick and my development stick.  On a related note, if we add a test suite, it would make sense to have an optional environment variable that can be used to pin the serial number of the testing device.  This way we could make sure that we do not accidentally run the test suite on a production device.

[`PRESET_PASSPHRASE`]: https://www.gnupg.org/documentation/manuals/gnupg/Agent-PRESET_005fPASSPHRASE.html

**Comment by d-e-s-o** [comment] 2018-12-21 02:03
> The documentation for [`PRESET_PASSPHRASE`](https://www.gnupg.org/documentation/manuals/gnupg/Agent-PRESET_005fPASSPHRASE.html) refers to the “cache for the specified _keygrip_”, while `GET_PASSPHRASE` and `CLEAR_PASSPHRASE` just refer to cache IDs. I don’t know whether this is just inconsistent/outdated documentation, or whether `PRESET_PASSPHRASE` really only applies to keys managed by GPG.

Ah yeah, I was confused by that as well, but then I was hoping we could just try it out, except, I guess not :-) Thanks for clarifying. I see now that my version has the same problem. Probably not worth poking around.

> I agree. I think this will mostly benefit us – at least I noticed the problem when switching between my production stick and my development stick. On a related note, if we add a test suite, it would make sense to have an optional environment variable that can be used to pin the serial number of the testing device. This way we could make sure that we do not accidentally run the test suite on a production device.

Yep, that may prove useful.

**Comment by d-e-s-o** [comment] 2019-01-12 05:03
> On a related note, if we add a test suite, it would make sense to have an optional environment variable that can be used to pin the serial number of the testing device. This way we could make sure that we do not accidentally run the test suite on a production device.

While the idea is good, I feel like we can't implement this properly, given that we can't open a device by serial number. I have a production storage stick and if I were to leave it in along with a testing storage and a pro device, chances are that the production stick would be connected to as part of the tests and while it may not be used to run them, it would cause skipping of tests that I did not intend.

Do you see what I mean, Robin? Do you see a way around that?

**Comment by robinkrahl** [comment] 2019-01-12 09:05
But not running the Storage tests would be better than running them on your production device (which would happen with the current implementation), right?

Now for the Storage, we have the functions `NK_list_devices_by_cpuID` and `NK_connect_with_ID` but I did not yet implement them in the `nitrokey` crate as I’m not happy with their design.

Also, we have to keep in mind that the serial number is not reported correctly for Storage devices.  I think it would nevertheless be a good idea to have this option, even if it may not allow us to distinguish different Storage devices.

By the way, could you please check whether both your production and your development Storage stick report the same serial number?

**Comment by d-e-s-o** [comment] 2019-01-12 16:53
> But not running the Storage tests would be better than running them on your production device (which would happen with the current implementation), right?

Yeah, but I just unplug the production stick. The problem is that I also run other commands from the command line for testing and there is no way I will always think of setting this variable in a non-test context.

> Now for the Storage, we have the functions `NK_list_devices_by_cpuID` and `NK_connect_with_ID` but I did not yet implement them in the `nitrokey` crate as I’m not happy with their design.

Interesting. I was not aware of this function pair.

> Also, we have to keep in mind that the serial number is not reported correctly for Storage devices. I think it would nevertheless be a good idea to have this option, even if it may not allow us to distinguish different Storage devices.

Oh? Can you point me to the issue?

> By the way, could you please check whether both your production and your development Storage stick report the same serial number?

Checked, they are different.

**Comment by robinkrahl** [comment] 2019-01-12 17:05
> Yeah, but I just unplug the production stick. The problem is that I also run other commands from the command line for testing and there is no way I will always think of setting this variable in a non-test context.

I still don’t get why the current version is better for you or what the environment variable would change.  Could you describe a use case step by step?

> Oh? Can you point me to the issue?

The firmware version issue is https://github.com/Nitrokey/nitrokey-storage-firmware/issues/76 (we discussed that in one of the pull requests).

> Checked, they are different.

Good to know.  So at least the command does not return a static value.

**Comment by d-e-s-o** [comment] 2019-01-12 17:42
> I still don’t get why the current version is better for you or what the environment variable would change. Could you describe a use case step by step?

It doesn't help (at least me), that's the point. I have to unplug anyway for the two reasons outlined above. If the solution doesn't work in the presence of these constraints, it's no use.

> The firmware version issue is [Nitrokey/nitrokey-storage-firmware#76](https://github.com/Nitrokey/nitrokey-storage-firmware/issues/76) (we discussed that in one of the pull requests).

Ah, that problem. Thanks!

**Comment by robinkrahl** [comment] 2019-01-12 17:50
Ah, I interpreted your comment “we can't implement this properly” as if there was an implementation problem.

Well, I agree that it does not solve all problems, but I think it does solve the problem of executing the test suite on the wrong device by accident.  So far it did not happen to me, but I think it’s not that unlikely as I’m constantly switching between the Pro for signing my work and decrypting my password when fetching new mail and the Storage for development.

Maybe that is the misunderstanding here?  I don’t intend this to be a mechanism to select the device when testing, I just want to avoid running the test suite on the wrong device by accident.  (When I suggested the change, I did not see connecting multiple devices at the same time as a supported use case.)

**Comment by d-e-s-o** [comment] 2019-01-12 17:59
> Maybe that is the misunderstanding here?

Yeah, probably. I am also not totally against it if you have a use case (assuming reasonable implementation complexity). That should probably be implemented in `nitrokey-test`, right? Which would have the benefit that it would apply to the `nitrokey` tests as well.

> Now for the Storage, we have the functions NK_list_devices_by_cpuID and NK_connect_with_ID but I did not yet implement them in the nitrokey crate as I’m not happy with their design.

Out of curiosity, what is the problem you have with their design (I have not even looked them up, so I have no idea)?

**Comment by robinkrahl** [comment] 2019-01-12 18:11
> Out of curiosity, what is the problem you have with their design (I have not even looked them up, so I have no idea)?
- The list methods returns a string that contains the smart card ID, the SD card ID, and the USB bus and device number.  This should be a data structure instead of a string.
- The connect method requires a string returned by the list method, but you only need the USB bus and device number to connect to a Device.  It should only require the bus and device number (as integers, not as a single string).
- There is no reason to limit this to the Storage devices.  (Well, the Pro has no SD card ID to return in the list method, but otherwise.)  It should also be applicable for Pro devices.
- The list method has to be called before the connect method as it generates a mapping from string identifier to device.  Instead, the list method should open a new connection using the bus and device number.

**Comment by d-e-s-o** [comment] 2019-01-12 18:14
Ups, that sounds pretty bad indeed. Thanks for clarifying.

**Comment by robinkrahl** [comment] 2019-01-12 18:21
Suggestions:
1. We wait until we have better `libnitrokey` functions.
2. We then add a `--serial-number` and maybe a `--usb-path` option to `nitrocli`.
3. For the test: We change `nitrokey-test` to set these options if an environment variable set, or we change `nitrocli` to check an environment variable if the options are not set.

**Comment by d-e-s-o** [comment] 2019-01-12 18:48
Sounds great to me! Allow me to close this issue and open a new one for the further improvements you outlined.

**Closed** 2019-01-12 18:50 UTC

**Comment by robinkrahl** [comment] 2019-01-12 18:52
I think we can just add it to the list on the wiki and link to this discussion.

**Comment by d-e-s-o** [comment] 2019-01-12 18:54
Fine by me, too. I'll add it to the list.
